# This file should be in the root of the repository
# If one of the blocks is not needed, it can be deleted
version: 1
# Block of instructions for the build stage
build:
  language: golang
  version: 1.22.1
  build_commands:
    - go mod tidy
    - CGO_ENABLED=0 go build -a -ldflags="-s -w" -o ./app ./
  start_commands:
    - ./app
